#!/bin/zsh
# Mirror deal-engine knowledge (markdown only, never secrets) into the Obsidian vault so a
# terminal Claude Code session can work from the vault. Idempotent; regenerates the INDEX.
set -e
R=/Users/finnleyolds/Claude/deal-engine
V="/Users/finnleyolds/Library/Mobile Documents/iCloud~md~obsidian/Documents/Lead getter/Lead Getter/Deal Engine"
M=/Users/finnleyolds/.claude/projects/-Users-finnleyolds-Claude/memory
mkdir -p "$V/company" "$V/audit" "$V/routines" "$V/_memory" "$V/coffee"
stamp() { f="$1"; src="$2"; dst="$3"
  if head -1 "$f" | grep -q '^---$'; then cp "$f" "$dst"
  else { printf -- '---\ncreated: %s\nupdated: %s\ntags: [deal-engine, summit-clearance]\nsource: %s\n---\n' "$(date +%F)" "$(date +%F)" "$src"; cat "$f"; } > "$dst"; fi }
for f in "$R"/company/*.md; do stamp "$f" "company/$(basename "$f")" "$V/company/$(basename "$f")"; done
for f in "$R"/company/audit/*.md(N); do stamp "$f" "company/audit/$(basename "$f")" "$V/audit/$(basename "$f")"; done
for f in "$R"/company/routines/*.md(N); do stamp "$f" "company/routines/$(basename "$f")" "$V/routines/$(basename "$f")"; done
[ -e "$R/.coffee/backlog.md" ] && stamp "$R/.coffee/backlog.md" ".coffee/backlog.md" "$V/coffee/backlog.md"
for f in "$M"/deal-engine*.md "$M"/hd-hidden-clearance-crack.md "$M"/tcg-restock-bot-reuse.md "$M"/apify-actor-economics.md "$M"/target-sweep-data-transfer.md "$M"/work-conservatively.md; do [ -e "$f" ] && cp "$f" "$V/_memory/$(basename "$f")"; done
# secret-VALUE guard (warn loudly; never copies .env or json)
if grep -rlE 'sk_live_[A-Za-z0-9]{8,}|whsec_[A-Za-z0-9]{8,}|scp-live-[A-Za-z0-9]{8,}|postgres(ql)?://[^ ]+:[^ ]+@' "$V" 2>/dev/null; then echo "WARN: possible secret VALUE in the files above — review"; fi
{ printf -- '---\ncreated: 2026-09-03\nupdated: %s\ntags: [deal-engine, summit-clearance, index]\n---\n# Deal Engine — INDEX (auto-generated by scripts/vault-sync.sh)\n\nRepo: `/Users/finnleyolds/Claude/deal-engine` · Live: https://summitclearance.com · Deploy: `git push origin main` then the Railway redeploy in [[_memory/deal-engine-railway-deploy]].\n\n## Start here\n- [[00 — Owner Mandate 2026-09-03 (24h launch sprint)]]\n- [[01 — Launch Strategy 2026-09]]\n- [[02 — Sprint Ledger 2026-09-03]]\n\n' "$(date +%F)"
  for d in company audit routines coffee _memory; do printf '## %s\n' "$d"; for f in "$V/$d"/*.md(N); do printf -- '- [[%s/%s]]\n' "$d" "$(basename "${f%.md}")"; done; printf '\n'; done
} > "$V/Deal Engine — INDEX.md"
echo "vault synced: $(find "$V" -name '*.md' | wc -l | tr -d ' ') notes in $V"
